---

- name: install dependencies
  apt: name=unzip
  become: yes
  become_user: root

- name: copy script
  template:
    src: build_geonames.sh.j2
    dest: "{{ ansible_user_dir }}"
    mode: 0755

- name: import data
  command: /bin/bash "{{ ansible_user_dir }}/build_geonames.sh"
